### PR TITLE
Do not call the stream view

### PR DESCRIPTION
**Pull request by ale-rt**
There is no more any need to call the stream view before rendering the tile

### CODE REVIEW

**Comment by pysailor** [comment]
This PR should become obsolete if #9 is accepted

**Comment by gyst** [comment]
This is not a valid solution. The postbox tile should be responsible for handling the new post submit request. This is currently handled by the stream, which mixes concerns.

Removing the stream call is half of the solution, the other half being that the postbox tile should call the appropriate update method directly on the microblog provider. This should be factored out of the stream base and into the microblog postbox
https://github.com/cosent/plonesocial.core/blob/master/src/plonesocial/core/browser/stream.py#L30

#8 is still a hack in this regards, since we then implicitly rely on a re-rendering of the stream to inject a new post.

**Comment by gyst** [comment]
This PR should be extended and supersede #9.

**Comment by ale-rt** [comment]
this does not make sense anymore, the tile is now here: https://github.com/cosent/plonesocial.microblog/blob/master/src/plonesocial/microblog/browser/tiles/newpostbox.py

**Pull request closed without merging**
