### PR TITLE
Add mention and tag picker using patternslib

### PR DESCRIPTION
**Pull request by tax**
Using patternslib to pick tags and mention users (round trip to server needed).
For reference implementation using js: https://github.com/cosent/plonesocial.microblog/pull/27

Remarks: Not sure where I should put the extra css styling?

### CODE REVIEW

**Comment by gyst** [comment]
There should not be any custom css.

**Comment by tax** [comment]
The css is added for two reasons:
1. Hide the picked users and tags in the list so they dont get rendered in the picker popup (maybe there is a hidden class but I did not find it)
2. To make sure the tags and users selected dont have each line for a selected item in the status update form.

I am not sure how to solve those by not adding extra css, mabye the css should be added to microblog?

**Comment by tax** [comment]
I removed the code for hiding since this is conditional in TAL and no visible html is rendered

**Comment by ebrehault** [comment]
The code looks good to me.
On the functional point of view, I have identified 2 problems:
- previously selected values are not pre-selected when we re-open the panel (we should pass them as parameter when loading the panel),
- once selected and panel closed, we cannot remove a selected value even by re-openning the panel.

**Comment by tax** [comment]
I updated this PR to use  [pat-checklist-picker](https://github.com/ploneintranet/pat-checklist-picker) pattern. This enables the picker to preserve state and keep everything on the clientside.

Also see this PR:
https://github.com/ploneintranet/ploneintranet.theme/pull/96/files

**Comment by tax** [comment]
@ebrehault can you please have a look at this update I think this is the way it should be.

**Comment by tax** [comment]
Making new PR to retrigger jenkins

**Pull request closed without merging**
